---
- name: Network Getting Started First Playbook
  connection: local
  hosts: localhost
  tasks:
    - name: kubeconfig
      command: aws eks --region us-east-1 update-kubeconfig --name demo-luca
    - name: deploy
      command: kubectl apply -f deployment.yaml
    # - name: load-balancer
    #   command: kubectl expose deployment imagem-cloud --type=LoadBalancer --port=80
    - name: autoscaler
      command: kubectl autoscale deployment imagem-cloud --cpu-percent=50 --min=1 --max=10
      